[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "3vTaTzgXpECzZmL4WVPLaGXHx4gnpoNs71Q1hKUNPiaE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/divij/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
