[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace = "FWVP24pdVC4x7Y1PabYKMQYxU8arfK34XSZXazCnbNTh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/divij/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
